In [4]:
#Q1

x=[[1,2,3],
  [4,5,6],
  [7,8,9]]
y=[[1,2,3],
  [4,5,6],
  [7,8,9]]
result=[[0,0,0],
       [0,0,0],
        [0,0,0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        result[i][j]=x[i][j]+y[i][j]
for r in result:
    print(r)

[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


In [6]:
#Q2

x=[[1,2,3],
  [4,5,6],
  [7,8,9]]
y=[[1,2,3],
  [4,5,6],
  [7,8,9]]
result=[[0,0,0],
       [0,0,0],
        [0,0,0]]
for i in range(len(x)):
    for j in range(len(y[0])):
        for k in range(len(y)):
            result[i][j]+=x[i][k]*y[k][j]
for r in result:
    print(r)

[30, 36, 42]
[66, 81, 96]
[102, 126, 150]


In [3]:
#Q3
import numpy as np
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

 
result= [[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]
 
result = np.dot(A,B)
 
for r in result:
    print(r)


[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


In [5]:
#Q4
import numpy as np
  
  
A = np.array([[1, 2], [3, 4]])
  
B = np.array([[4, 5], [6, 7]])
  
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
  
print("Addition of two matrix")
print(np.add(A, B))

print("Subtraction of two matrix")
print(np.subtract(A,B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [7]:
#Q5
import numpy 
matrix=[[1,2,3],[4,5,6]]
print(matrix)
print("\n")
print(numpy.transpose(matrix))

[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


In [9]:
#Q6

N = 4

print("The dimension : " + str(N))
  
res = [list(range(1 + N * i, 1 + N * (i + 1)))
                            for i in range(N)]
  
print("The created matrix of N * N: " + str(res))

The dimension : 4
The created matrix of N * N: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [11]:
#Q7

test_list = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
  
print("The original list is : " + str(test_list))
  
K = 2
  
res = [sub[K-1] for sub in test_list]

print("The Kth column of matrix is : " + str(res))

The original list is : [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
The Kth column of matrix is : [5, 1, 12]


In [14]:
#Q8
test_list = [["ineuron", "good"], ["is", "for"], ["business","analyst"]]
  
print("The original list : " + str(test_list))
  
res = []
N = 0
while N != len(test_list):
    temp = ''
    for idx in test_list:
        try: temp = temp + idx[N]
        except IndexError: pass
    res.append(temp)
    N = N + 1
  
res = [ele for ele in res if ele]
  

print("List after column Concatenation : " + str(res))

The original list : [['ineuron', 'good'], ['is', 'for'], ['business', 'analyst']]
List after column Concatenation : ['ineuronisbusiness', 'goodforanalyst']


In [15]:
#Q9
def isPalindrome(s):
    return s == s[::-1]
 
 
s = "malayalam"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")

Yes


In [16]:
#Q10
def check_sym(string):
    n=len(string)
    flag=0
    if n%2:
        mid=n//2+1
    else:
        mid= n//2
    start=0
    end= mid
    while(start <mid and end<n):
        if(string[start]== string[end]):
            start= start+1
            end= end+1
        else:
            flag=1
            break
    if flag==0:
        print("symmetrical")
    else:
        print("not symmetrical")

s= "abcabc"
print (s)
check_sym(s)
s2= "abcdab"
print(s2)
check_sym(s2)

abcabc
symmetrical
abcdab
not symmetrical
